src/homework/courseapp/urls.py
from django.urls import include, path

from . import views

app_name = 'courseapp'

urlpatterns = [
    path(
        'teacher/',
        include(
            [
               path('courses/', views.TeacherCoursesView.as_view(), name='teacher_courses'),
               path('new_course/', views.NewCourseView.as_view(), name='new_course'),
               path('update_course/<int:pk>/', views.CourseUpdateView.as_view(), name='update_course'),
               path('new_presentation/<int:course_id>/', views.NewPresentationView.as_view(), name='new_presentation'),
               path(
                   'course_presentations/<int:pk>/',
                   views.CoursePresentationsView.as_view(),
                   name='course_presentations'
               ),
               path(
                   'manage_presentation/<int:pk>/',
                   views.ManagePresentationView.as_view(),
                   name='manage_presentation'
               ),
               path('new_homework/<int:presentation_id>/', views.NewHomeworkView.as_view(), name='new_homework'),
               path('homework_details/<int:pk>/', views.HomeworkDetailsView.as_view(), name='homework_details'),
               path('update_grade/<int:pk>/', views.UpdateGradeView.as_view(), name='update_grade'),
               path('attendancy_details/<int:pk>/', views.AttendancyDetailsView.as_view(), name='attendancy_details'),
               path('new_lecture/<int:presentation_id>/', views.NewLectureView.as_view(), name='new_lecture')
            ]
        )
    ),
    path(
        'student/',
        include(
          [
              path('join_presentation/<int:pk>/', views.JoinPresentationView.as_view(), name='join_presentation'),
              path('submit_answer/<int:homework_id>/', views.SubmitAnswerView.as_view(), name='submit_answer'),
              path('courses/', views.StudentCoursesView.as_view(), name='student_courses'),
              path('course_dashboard/<int:pk>/', views.PresentationDashboardView.as_view(), name='course_dashboard')
          ]
        )
     ),
    path('course_details/<int:pk>/', views.CourseDetailsView.as_view(), name='course_details'),
    path('lecture_details/<int:pk>/', views.LectureDetailsView.as_view(), name='lecture_details'),
    path(
        'certificate_details/<int:presentation_id>/<int:student_id>/',
        views.CertificateDetailsView.as_view(),
        name='certificate_details'
     )
]

src/homework/homework/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('interface.urls')),
    path('users/', include('userapp.urls')),
    path('courses/', include('courseapp.urls')),
    path('admin/', admin.site.urls)
]

src/homework/userapp/urls.py
from django.urls import path

from . import views

app_name = 'userapp'

urlpatterns = [
    path('sign_up/', views.SignUpView.as_view(), name='sign_up'),
    path('sign_in/', views.SingInView.as_view(), name='sign_in'),
    path('sign_out/', views.SignOutView.as_view(), name='sign_out'),
    path('profile/<int:pk>/', views.TeacherProfileView.as_view(), name='teacher_profile')
]

src/homework/courseapp/models.py
from django.db import models
from django.urls import reverse
from django.utils.timezone import now


class Course(models.Model):
    name = models.CharField('course name', max_length=128, unique=True, blank=False, null=False)
    description = models.TextField(blank=False, null=False)
    teacher = models.ForeignKey('userapp.Teacher', on_delete=models.CASCADE, null=False, blank=False)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('courseapp:course_details', kwargs={'pk': self.id})

    def get_active_presentations(self):
        return self.presentation_set.filter(start_date__lte=now().date(), end_date__gte=now().date())

    def get_attendable_presentations(self):
        return self.presentation_set.filter(start_date__gte=now().date())


class PresentationStudentRel(models.Model):
    class Meta:
        constraints = [models.UniqueConstraint(fields=['student', 'presentation'], name='unique attendancy')]

    student = models.ForeignKey('userapp.Student', on_delete=models.CASCADE)
    presentation = models.ForeignKey('courseapp.Presentation', on_delete=models.CASCADE)
    grade = models.IntegerField(blank=False, null=False, default=0)

    def get_absolute_url(self):
        return reverse('courseapp:attendancy_details', kwargs={'pk': self.id})


class Presentation(models.Model):
    start_date = models.DateField('start date', null=False, blank=False)
    end_date = models.DateField('end date', null=False, blank=False)
    course = models.ForeignKey('courseapp.Course', on_delete=models.CASCADE, null=False, blank=False)
    students = models.ManyToManyField('userapp.Student', through=PresentationStudentRel)

    def is_active(self):
        return (self.start_date <= now().date()) and (self.end_date >= now().date())

    def is_attendable(self):
        return self.start_date >= now().date()

    def __str__(self):
        return f'{str(self.course)}: {self.start_date} - {self.end_date}'


class HomeworkStudentRel(models.Model):
    class Meta:
        constraints = [models.UniqueConstraint(fields=['student', 'homework'], name='unique answer')]

    student = models.ForeignKey('userapp.Student', on_delete=models.CASCADE, blank=False, null=False)
    homework = models.ForeignKey('courseapp.Homework', on_delete=models.CASCADE, blank=False, null=False)
    answer = models.TextField(blank=False, null=False)


class Homework(models.Model):
    title = models.CharField(max_length=128, blank=False, null=False)
    description = models.TextField(blank=False, null=False)
    presentation = models.ForeignKey('courseapp.Presentation', on_delete=models.CASCADE, blank=False, null=False)
    answers = models.ManyToManyField('userapp.Student', through=HomeworkStudentRel)

    def __str__(self):
        return self.title


class Lecture(models.Model):
    title = models.CharField(max_length=128, blank=False, null=False)
    text = models.TextField(blank=False, null=False)
    presentation = models.ForeignKey('courseapp.Presentation', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

src/homework/userapp/models.py
from courseapp.models import HomeworkStudentRel, PresentationStudentRel
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models


class User(AbstractUser):
    objects = UserManager()

    class Types(models.TextChoices):
        TEACHER = ('TEACHER', 'Teacher')
        STUDENT = ('STUDENT', 'Student')

    user_type = models.CharField(max_length=8, choices=Types.choices, null=False, blank=False)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class TeacherManager(UserManager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(user_type=User.Types.TEACHER)


class Teacher(User):
    class Meta:
        proxy = True

    objects = TeacherManager()

    def save(self, *args, **kwargs):
        if not self.pk:
            self.user_type = User.Types.TEACHER
        super().save(*args, **kwargs)


class StudentManager(UserManager):
    def get_queryset(self, *args, **kwargs):
        return super().get_queryset(*args, **kwargs).filter(user_type=User.Types.STUDENT)


class Student(User):
    class Meta:
        proxy = True

    objects = StudentManager()

    def has_taken(self, course):
        return PresentationStudentRel.objects.filter(presentation__course=course).filter(student=self).exists()

    def has_attended(self, presentation):
        return PresentationStudentRel.objects.filter(presentation=presentation).filter(student=self).exists()

    def has_answered(self, homework):
        return HomeworkStudentRel.objects.filter(homework=homework).filter(student=self).exists()

    def save(self, *args, **kwargs):
        if not self.pk:
            self.user_type = User.Types.STUDENT
        super().save(*args, **kwargs)

src/homework/userapp/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class UserInfoForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'password1', 'password2', 'first_name', 'last_name', 'email', 'user_type')

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        for field in ['username', 'password1', 'password2']:
            self.fields[field].help_text = None
        for field in list(set(self.fields) - {'user_type'}):
            self.fields[field].widget.attrs.update({'class': 'form-control'})
        self.fields['user_type'].widget.attrs.update({'class': 'form-select'})

    first_name = forms.CharField(max_length=150, required=True)
    last_name = forms.CharField(max_length=150, required=True)
    email = forms.EmailField(max_length=254, required=True)


class SignInForm(AuthenticationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in list(set(self.fields) - {'user_type'}):
            self.fields[field].widget.attrs.update({'class': 'form-control'})
        self.fields['username'].widget.attrs.update({'autofocus': False})

src/homework/userapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.views import generic

from .forms import SignInForm, UserInfoForm
from .models import Teacher
from .utils import AnonymousOnlyViewMixin

# Create your views here.


class SignUpView(AnonymousOnlyViewMixin, generic.CreateView):
    template_name = 'userapp/sign_up.html'
    form_class = UserInfoForm
    success_url = reverse_lazy('userapp:sign_in')

    def get_context_data(self, *args, **kwargs):
        cxt = super().get_context_data(*args, **kwargs)
        cxt.update({'title': 'Sign up'})
        return cxt


class SingInView(AnonymousOnlyViewMixin, LoginView):
    template_name = 'userapp/sign_in.html'
    form_class = SignInForm

    def get_context_data(self, *args, **kwargs):
        cxt = super().get_context_data(*args, **kwargs)
        cxt.update({'title': 'Sign in'})
        return cxt


class SignOutView(LoginRequiredMixin, LogoutView):
    pass


class TeacherProfileView(generic.DetailView):
    model = Teacher
    template_name = 'userapp/teacher_profile.html'

    def get_context_data(self, *args, **kwargs):
        cxt = super().get_context_data(*args, **kwargs)
        cxt.update({'title': f'{self.object.first_name} {self.object.last_name}'})
        return cxt

src/homework/userapp/templates/userapp/sign_in.html
{% extends 'main/base.html' %}
{% block bodytag %}
    <h2 class="page-title">Sign in</h2>
    <hr>
    <form action="" method="POST" class="compact-form">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username" class="form-label">Username:</label>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Password:</label>
            {{ form.password }}
        </div>
        <input type="submit" class="btn btn-dark btn-sm" value="Login">
    </form>
{% endblock bodytag %}

src/homework/userapp/templates/userapp/sign_up.html
{% extends 'main/base.html' %}
{% block bodytag %}
    <h2 class="page-title">Sign up</h2>
    <hr>
    <form action="" method="POST" class="compact-form">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username" class="form-label">Username:</label>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label for="first_name" class="form-label">First name:</label>
            {{ form.first_name }}
        </div>
        <div class="mb-3">
            <label for="last_name" class="form-label">Last name:</label>
            {{ form.last_name }}
        </div>
        <div class="mb-3">
            <label for="email" class="form-label">Email:</label>
            {{ form.email }}
        </div>
        <div class="mb-3">
            <label for="password1" class="form-label">Password:</label>
            {{ form.password1 }}
        </div>
        <div class="mb-3">
            <label for="password2" class="form-label">Password confirmation:</label>
            {{ form.password2 }}
        </div>
        <div class="mb-3">
            <label for="user_type" class="form-label">Role:</label>
            {{ form.user_type }}
        </div>
        <input type="submit" class="btn btn-dark btn-sm" value="Register">
    </form>
{% endblock bodytag %}

src/homework/userapp/templates/userapp/teacher_profile.html
{% extends 'main/base.html' %}
{% block bodytag %}
    <h4>Courses by {{ teacher }}</h4>
    <hr>
    {% if teacher.course_set.all %}
        <div class="row row-cols-1 row-cols-md-2 g-4">
            {% for course in teacher.course_set.all %}
            <div class="col" >
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ course }}</h5>
                        <p class="card-text">{{ course.description|truncatechars:256 }}</p>
                        {% if course.get_attendable_presentations %}
                            <a href="{% url 'courseapp:course_details' course.id %}" class="btn btn-sm btn-dark" role="button">Details</a>
                        {% else %}
                            <a href="{% url 'courseapp:course_details' course.id %}" class="btn btn-sm btn-light" role="button">Details</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    {% else %}
        <h4>No available courses found</h4>
    {% endif %}
{% endblock bodytag %}