src/homework/courseapp/urls.py
from django.urls import include, path

from . import views

app_name = 'courseapp'

urlpatterns = [
    path(
        'teacher/',
        include(
            [
               path('courses/', views.TeacherCoursesView.as_view(), name='teacher_courses'),
               path('new_course/', views.NewCourseView.as_view(), name='new_course'),
               path('update_course/<int:pk>/', views.CourseUpdateView.as_view(), name='update_course'),
               path('new_presentation/<int:course_id>/', views.NewPresentationView.as_view(), name='new_presentation'),
               path(
                   'course_presentations/<int:pk>/',
                   views.CoursePresentationsView.as_view(),
                   name='course_presentations'
               ),
               path(
                   'manage_presentation/<int:pk>/',
                   views.ManagePresentationView.as_view(),
                   name='manage_presentation'
               ),
               path('new_homework/<int:presentation_id>/', views.NewHomeworkView.as_view(), name='new_homework'),
               path('homework_details/<int:pk>/', views.HomeworkDetailsView.as_view(), name='homework_details'),
               path('update_grade/<int:pk>/', views.UpdateGradeView.as_view(), name='update_grade'),
               path('attendancy_details/<int:pk>/', views.AttendancyDetailsView.as_view(), name='attendancy_details'),
               path('new_lecture/<int:presentation_id>/', views.NewLectureView.as_view(), name='new_lecture')
            ]
        )
    ),
    path(
        'student/',
        include(
          [
              path('join_presentation/<int:pk>/', views.JoinPresentationView.as_view(), name='join_presentation'),
              path('submit_answer/<int:homework_id>/', views.SubmitAnswerView.as_view(), name='submit_answer'),
              path('courses/', views.StudentCoursesView.as_view(), name='student_courses'),
              path('course_dashboard/<int:pk>/', views.PresentationDashboardView.as_view(), name='course_dashboard')
          ]
        )
     ),
    path('course_details/<int:pk>/', views.CourseDetailsView.as_view(), name='course_details'),
    path('lecture_details/<int:pk>/', views.LectureDetailsView.as_view(), name='lecture_details'),
    path(
        'certificate_details/<int:presentation_id>/<int:student_id>/',
        views.CertificateDetailsView.as_view(),
        name='certificate_details'
     )
]

src/homework/homework/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('interface.urls')),
    path('users/', include('userapp.urls')),
    path('courses/', include('courseapp.urls')),
    path('admin/', admin.site.urls)
]

src/homework/interface/urls.py
from django.urls import path

from . import views

app_name = 'interface'

urlpatterns = [path('', views.Index.as_view(), name='index')]

src/homework/userapp/urls.py
from django.urls import path

from . import views

app_name = 'userapp'

urlpatterns = [
    path('sign_up/', views.SignUpView.as_view(), name='sign_up'),
    path('sign_in/', views.SingInView.as_view(), name='sign_in'),
    path('sign_out/', views.SignOutView.as_view(), name='sign_out'),
    path('profile/<int:pk>/', views.TeacherProfileView.as_view(), name='teacher_profile')
]

src/homework/interface/views.py
from courseapp.models import Course
from django.views import generic

# Create your views here.


class Index(generic.ListView):
    template_name = 'interface/index.html'
    context_object_name = 'course_set'

    def get_queryset(self):
        return Course.objects.all().order_by('-id')[:6]

    def get_context_data(self, *args, **kwargs):
        cxt = super().get_context_data(*args, **kwargs)
        cxt.update({'title': 'Homepage'})
        return cxt

src/homework/interface/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Homework - {{ title }}</title>
    <link rel="icon" href="{% static 'main/img/favicon.png' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        .page-title {
            display: block;
            text-align: center;
            padding: 1%;
        }
        .compact-form {
            max-width: 50%;
            margin: auto;
        }
    </style>
    {% block headtag %}
    {% endblock headtag %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top container">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'interface:index' %}">Homework</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if not request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'userapp:sign_up' %}">Sign up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'userapp:sign_in' %}">Sign in</a>
                        </li>
                    {% else %}
                        {% if request.user.user_type == 'STUDENT' %}
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'courseapp:student_courses' %}">Courses</a>
                            </li>
                        {% elif request.user.user_type == 'TEACHER' %} 
                            <li class="nav-item">
                                <a class="nav-link" aria-current="page" href="{% url 'courseapp:teacher_courses' %}">Courses</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'userapp:teacher_profile' request.user.id %}">Profile</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'userapp:sign_out' %}">Sign out</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="https://github.com/amirongit/Homework" target="_blank">Source code</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <br>
        {% block bodytag %}
        {% endblock bodytag %}
        <br>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>