src/homework/courseapp/urls.py
from django.urls import include, path

from . import views

app_name = 'courseapp'

urlpatterns = [
    path(
        'teacher/',
        include(
            [
               path('courses/', views.TeacherCoursesView.as_view(), name='teacher_courses'),
               path('new_course/', views.NewCourseView.as_view(), name='new_course'),
               path('update_course/<int:pk>/', views.CourseUpdateView.as_view(), name='update_course'),
               path('new_presentation/<int:course_id>/', views.NewPresentationView.as_view(), name='new_presentation'),
               path(
                   'course_presentations/<int:pk>/',
                   views.CoursePresentationsView.as_view(),
                   name='course_presentations'
               ),
               path(
                   'manage_presentation/<int:pk>/',
                   views.ManagePresentationView.as_view(),
                   name='manage_presentation'
               ),
               path('new_homework/<int:presentation_id>/', views.NewHomeworkView.as_view(), name='new_homework'),
               path('homework_details/<int:pk>/', views.HomeworkDetailsView.as_view(), name='homework_details'),
               path('update_grade/<int:pk>/', views.UpdateGradeView.as_view(), name='update_grade'),
               path('attendancy_details/<int:pk>/', views.AttendancyDetailsView.as_view(), name='attendancy_details'),
               path('new_lecture/<int:presentation_id>/', views.NewLectureView.as_view(), name='new_lecture')
            ]
        )
    ),
    path(
        'student/',
        include(
          [
              path('join_presentation/<int:pk>/', views.JoinPresentationView.as_view(), name='join_presentation'),
              path('submit_answer/<int:homework_id>/', views.SubmitAnswerView.as_view(), name='submit_answer'),
              path('courses/', views.StudentCoursesView.as_view(), name='student_courses'),
              path('course_dashboard/<int:pk>/', views.PresentationDashboardView.as_view(), name='course_dashboard')
          ]
        )
     ),
    path('course_details/<int:pk>/', views.CourseDetailsView.as_view(), name='course_details'),
    path('lecture_details/<int:pk>/', views.LectureDetailsView.as_view(), name='lecture_details'),
    path(
        'certificate_details/<int:presentation_id>/<int:student_id>/',
        views.CertificateDetailsView.as_view(),
        name='certificate_details'
     )
]

src/homework/homework/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('interface.urls')),
    path('users/', include('userapp.urls')),
    path('courses/', include('courseapp.urls')),
    path('admin/', admin.site.urls)
]

src/homework/userapp/urls.py
from django.urls import path

from . import views

app_name = 'userapp'

urlpatterns = [
    path('sign_up/', views.SignUpView.as_view(), name='sign_up'),
    path('sign_in/', views.SingInView.as_view(), name='sign_in'),
    path('sign_out/', views.SignOutView.as_view(), name='sign_out'),
    path('profile/<int:pk>/', views.TeacherProfileView.as_view(), name='teacher_profile')
]

src/homework/courseapp/models.py
from django.db import models
from django.urls import reverse
from django.utils.timezone import now


class Course(models.Model):
    name = models.CharField('course name', max_length=128, unique=True, blank=False, null=False)
    description = models.TextField(blank=False, null=False)
    teacher = models.ForeignKey('userapp.Teacher', on_delete=models.CASCADE, null=False, blank=False)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse('courseapp:course_details', kwargs={'pk': self.id})

    def get_active_presentations(self):
        return self.presentation_set.filter(start_date__lte=now().date(), end_date__gte=now().date())

    def get_attendable_presentations(self):
        return self.presentation_set.filter(start_date__gte=now().date())


class PresentationStudentRel(models.Model):
    class Meta:
        constraints = [models.UniqueConstraint(fields=['student', 'presentation'], name='unique attendancy')]

    student = models.ForeignKey('userapp.Student', on_delete=models.CASCADE)
    presentation = models.ForeignKey('courseapp.Presentation', on_delete=models.CASCADE)
    grade = models.IntegerField(blank=False, null=False, default=0)

    def get_absolute_url(self):
        return reverse('courseapp:attendancy_details', kwargs={'pk': self.id})


class Presentation(models.Model):
    start_date = models.DateField('start date', null=False, blank=False)
    end_date = models.DateField('end date', null=False, blank=False)
    course = models.ForeignKey('courseapp.Course', on_delete=models.CASCADE, null=False, blank=False)
    students = models.ManyToManyField('userapp.Student', through=PresentationStudentRel)

    def is_active(self):
        return (self.start_date <= now().date()) and (self.end_date >= now().date())

    def is_attendable(self):
        return self.start_date >= now().date()

    def __str__(self):
        return f'{str(self.course)}: {self.start_date} - {self.end_date}'


class HomeworkStudentRel(models.Model):
    class Meta:
        constraints = [models.UniqueConstraint(fields=['student', 'homework'], name='unique answer')]

    student = models.ForeignKey('userapp.Student', on_delete=models.CASCADE, blank=False, null=False)
    homework = models.ForeignKey('courseapp.Homework', on_delete=models.CASCADE, blank=False, null=False)
    answer = models.TextField(blank=False, null=False)


class Homework(models.Model):
    title = models.CharField(max_length=128, blank=False, null=False)
    description = models.TextField(blank=False, null=False)
    presentation = models.ForeignKey('courseapp.Presentation', on_delete=models.CASCADE, blank=False, null=False)
    answers = models.ManyToManyField('userapp.Student', through=HomeworkStudentRel)

    def __str__(self):
        return self.title


class Lecture(models.Model):
    title = models.CharField(max_length=128, blank=False, null=False)
    text = models.TextField(blank=False, null=False)
    presentation = models.ForeignKey('courseapp.Presentation', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

src/homework/courseapp/views.py
from django.db import IntegrityError
from django.http import Http404
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.timezone import now
from django.views import generic

from userapp.models import Student, Teacher, User
from userapp.utils import StudentOnlyViewMixin, TeacherOnlyViewMixin

from .forms import (
    AnswerSubmitionForm,
    CourseInfoForm,
    GradeUpdateForm,
    HomeworkCreationForm,
    LectureInforForm,
    PresentationCreationForm
)
from .models import (
    Course,
    Homework,
    HomeworkStudentRel,
    Lecture,
    Presentation,
    PresentationStudentRel
)


class TeacherCoursesView(TeacherOnlyViewMixin, generic.ListView):
    template_name = 'courseapp/teacher_courses.html'
    context_object_name = 'course_set'

    def get_queryset(self):
        return Teacher.objects.get(pk=self.request.user.id).course_set.all()

    def get_context_data(self, *args, **kwargs):
        cxt = super().get_context_data(*args, **kwargs)
        cxt.update({'title': 'Courses'})
        return cxt


class NewCourseView(TeacherOnlyViewMixin, generic.CreateView):
    template_name = 'courseapp/new_course.html'
    form_class = CourseInfoForm

    def form_valid(self, form):
        course = form.save(commit=False)
        course.teacher = self.request.user
        course.save()
        return redirect(reverse('courseapp:teacher_courses'))

    def get_context_data(self, *args, **kwargs):
        cxt = super().get_context_data(*args, **kwargs)
        cxt.update({'title': 'New course'})
        return cxt


class CourseDetailsView(generic.DetailView):
    model = Course
    template_name = 'courseapp/course_details.html'

    def get_context_data(self, *args, **kwargs):
        cxt = super().get_context_data(*args, **kwargs)
        if (not self.request.user.is_anonymous) and (self.request.user.user_type == User.Types.STUDENT):
            taken = Student.objects.get(id=self.request.user.id).has_taken(Course.objects.get(id=self.object.id))
            cxt.update({'taken': taken})
        cxt.update({'title': self.object.name})
        return cxt


class CourseUpdateView(TeacherOnlyViewMixin, generic.UpdateView):
    model = Course
    form_class = CourseInfoForm
    template_name = 'courseapp/update_course.html'

    def test_func(self, *args, **kwargs):
        if super().test_func(*args, **kwargs):
            return self.get_object().teacher.id == self.request.user.id
        return False

    def get_context_data(self, *args, **kwargs):
        cxt = super().get_context_data(*args, **kwargs)
        cxt.update({'title': self.object.name})
        return cxt


class NewPresentationView(TeacherOnlyViewMixin, generic.CreateView):
    template_name = 'courseapp/new_presentation.html'
    form_class = PresentationCreationForm

    def test_func(self, *args, **kwargs):
        if super().test_func(*args, **kwargs):
            return Course.objects.get(id=self.kwargs['course_id']).teacher == self.request.user
        return False

    def form_valid(self, form):
        presentation = form.save(commit=False)
        presentation.course = Course.objects.get(id=self.kwargs['course_id'])
        presentation.save()
        return redirect(reverse('courseapp:course_presentations', kwargs=({'pk': self.kwargs['course_id']})))

    def get_context_data(self, *args, **kwargs):
        cxt = super().get_context_data(*args, **kwargs)
        cxt.update({'title': 'New presentation', 'course_name': Course.objects.get(id=self.kwargs['course_id']).name})
        return cxt


class CoursePresentationsView(TeacherOnlyViewMixin, generic.ListView):
    template_name = 'courseapp/course_presentations.html'
    context_object_name = 'presentation_set'

    def get_queryset(self):
        return Course.objects.get(id=self.kwargs['pk']).presentation_set.all()

    def test_func(self, *args, **kwargs):
        if super().test_func(*args, **kwargs):
            return Course.objects.get(id=self.kwargs['pk']).teacher.id == self.request.user.id
        return False

    def get_context_data(self, *args, **kwargs):
        cxt = super().get_context_data(*args, **kwargs)
        cxt.update({'title': Course.objects.get(id=self.kwargs['pk']).name, 'course_id': self.kwargs['pk']})
        return cxt


class JoinPresentationView(StudentOnlyViewMixin, generic.View):
    def test_func(self, *args, **kwargs):
        if super().test_func(*args, **kwargs):
            student = Student.objects.get(id=self.request.user.id)
            presentation = Presentation.objects.get(id=self.kwargs['pk'])
            return (
                not student.has_attended(presentation)
            ) and (
                not student.has_taken(presentation.course)
            ) and (
                presentation.is_attendable()
            )
        return False

    def get(self, request, pk):
        presentation = Presentation.objects.get(id=pk)
        student = Student.objects.get(id=request.user.id)
        rel_obj = PresentationStudentRel(student=student, presentation=presentation)
        try:
            rel_obj.save()
            return redirect(reverse('courseapp:student_courses'))
        except IntegrityError:
            return redirect(reverse('courseapp:course_details', kwargs={'pk': presentation.course.id}))


class ManagePresentationView(TeacherOnlyViewMixin, generic.DetailView):
    model = Presentation
    template_name = 'courseapp/manage_presentation.html'

    def test_func(self, *args, **kwargs):
        if super().test_func(*args, **kwargs):
            presentation = self.get_object()
            return (presentation.course.teacher.id == self.request.user.id) and (presentation.is_active())
        return False

    def get_context_data(self, *args, **kwargs):
        cxt = super().get_context_data(*args, **kwargs)
        cxt.update({'title': self.object.course.name})
        return cxt


class NewHomeworkView(TeacherOnlyViewMixin, generic.CreateView):
    model = Homework
    template_name = 'courseapp/new_homework.html'
    form_class = HomeworkCreationForm

    def test_func(self, *args, **kwargs):
        if super().test_func(*args, **kwargs):
            presentation = Presentation.objects.get(id=self.kwargs['presentation_id'])
            return (presentation.course.teacher.id == self.request.user.id) and (presentation.is_active())
        return False

    def get_context_data(self, *args, **kwargs):
        cxt = super().get_context_data(*args, **kwargs)
        cxt.update({'title': 'New homework'})
        return cxt

    def form_valid(self, form):
        homework = form.save(commit=False)
        homework.presentation = Presentation.objects.get(id=self.kwargs['presentation_id'])
        homework.save()
        return redirect(reverse('courseapp:manage_presentation', kwargs={'pk': self.kwargs['presentation_id']}))


class SubmitAnswerView(StudentOnlyViewMixin, generic.CreateView):
    model = HomeworkStudentRel
    template_name = 'courseapp/submit_answer.html'
    form_class = AnswerSubmitionForm

    def test_func(self, *args, **kwargs):
        if super().test_func(*args, **kwargs):
            homework = Homework.objects.get(id=self.kwargs['homework_id'])
            student = Student.objects.get(id=self.request.user.id)
            return (
                student.has_attended(homework.presentation)
            ) and (
                not student.has_answered(homework)
            ) and (
                homework.presentation.is_active()
            )
        return False

    def form_valid(self, form):
        answer = form.save(commit=False)
        answer.homework = Homework.objects.get(id=self.kwargs['homework_id'])
        answer.student = Student.objects.get(id=self.request.user.id)
        answer.save()
        return redirect(reverse('courseapp:course_dashboard', kwargs={'pk': answer.homework.presentation.id}))

    def get_context_data(self, *args, **kwargs):
        cxt = super().get_context_data(*args, **kwargs)
        cxt.update({'title': f'{Homework.objects.get(id=self.kwargs["homework_id"])}'})
        return cxt


class HomeworkDetailsView(TeacherOnlyViewMixin, generic.DetailView):
    model = Homework
    template_name = 'courseapp/homework_details.html'

    def test_func(self, *args, **kwargs):
        if super().test_func(*args, **kwargs):
            return self.get_object().presentation.course.teacher.id == self.request.user.id
        return False

    def get_context_data(self, *args, **kwargs):
        cxt = super().get_context_data(*args, **kwargs)
        cxt.update({'title': f'{self.get_object().title}'})
        return cxt


class UpdateGradeView(TeacherOnlyViewMixin, generic.UpdateView):
    model = PresentationStudentRel
    form_class = GradeUpdateForm
    template_name = 'courseapp/update_grade.html'

    def test_func(self, *args, **kwargs):
        if super().test_func(*args, **kwargs):
            presentation = self.get_object().presentation
            return (
                presentation.course.teacher.id == self.request.user.id
            ) and (
                presentation.is_active()
            )
        return False

    def get_context_data(self, *args, **kwargs):
        cxt = super().get_context_data(*args, **kwargs)
        cxt.update({'title': f'Update {self.get_object().student}'})
        return cxt


class AttendancyDetailsView(TeacherOnlyViewMixin, generic.DetailView):
    model = PresentationStudentRel
    template_name = 'courseapp/attendancy_details.html'

    def get_context_data(self, *args, **kwargs):
        cxt = super().get_context_data(*args, **kwargs)
        cxt.update(
            {
                'title': f'{self.get_object().student}',
                'homework_set': HomeworkStudentRel.objects.filter(
                    homework__presentation=self.get_object().presentation
                ).filter(
                    student=self.get_object().student
                )
            }
        )

src/homework/courseapp/templates/courseapp/attendancy_details.html
{% extends 'main/base.html' %}
{% block bodytag %}
    <h2>{{ presentationstudentrel.student }} | {{ presentationstudentrel.grade }}</h2>
    <hr>
    {% if homework_set.all %}
        {% for homework in homework_set.all %}
            <div class="card">
                <div class="card-header">{{ homework.homework.title }}</div>
                <div class="card-body">
                    <p class="card-text">{{ homework.answer }}</p>
                </div>
            </div>
            <br>
        {% endfor %}
    {% else %}
        <h4>No available answers found</h4>
    {% endif %}
{% endblock bodytag %}

src/homework/courseapp/templates/courseapp/certificate_details.html
{% extends 'main/base.html' %}
{% block bodytag %}
    <h2>{{ presentationstudentrel.course }} certificate</h2>
    <hr>
    <p>
        We confirm that {{ presentationstudentrel.student }} has taken {{ presentationstudentrel.presentation.course }} course on Homework platform.<br>
        issued on: {{ presentationstudentrel.presentation.end_date }}
    </p>
{% endblock bodytag %}

src/homework/courseapp/templates/courseapp/course_create.html
{% extends 'main/base.html' %}
{% block content %}
<form action="" method="POST">
    {{ form }}
    <input type="submit" value="Create">
</form>
{% endblock %}

src/homework/courseapp/templates/courseapp/course_details.html
{% extends 'main/base.html' %}
{% block bodytag %}
    <h2>{{ course }}</h2>
    <span class="text-muted">by <a href="{% url 'userapp:teacher_profile' course.teacher.id %}" class="text-reset">{{ course.teacher }}</a></span>
    <hr>
    <p>{{ course.description }}</p>
    <br>
    <h4>Presentations</h4>
    <hr>
    {% if course.get_attendable_presentations %}
        {% if user.is_anonymous or user.user_type == 'TEACHER' %}
            <table class="table">
                <thead>
                    <th scope="col">Start date</th>
                    <th scope="col">End date</th>
                </thead>
                <tbody>
                    {% for presentation in course.get_attendable_presentations %}
                        <tr>
                            <td>{{ presentation.start_date }}</td>
                            <td>{{ presentation.end_date }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% elif not taken %}
            <table class="table">
                <thead>
                    <th scope="col">Start date</th>
                    <th scope="col">End date</th>
                </thead>
                <tbody>
                    {% for presentation in course.get_attendable_presentations %}
                        <tr>
                            <td>{{ presentation.start_date }}</td>
                            <td>{{ presentation.end_date }}</td>
                            <td><a href="{% url 'courseapp:join_presentation' presentation.id %}" class="btn btn-sm btn-dark" role="button">Attend</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <h4>Course already taken</h4>
        {% endif %}
    {% else %}
        <h4>No available presentations found</h4>
    {% endif %}
{% endblock bodytag %}

src/homework/courseapp/templates/courseapp/course_presentations.html
{% extends 'main/base.html' %}
{% block bodytag %}
    <a href="{% url 'courseapp:new_presentation' course_id %}" class="btn btn-dark">New presentation</a>
    <hr>
    {% if presentation_set %}
        <table class="table">
            <thead>
                <th scope="col">Start date</th>
                <th scope="col">End date</th>
            </thead>
            <tbody>
                {% for presentation in presentation_set %}
                    <tr>
                        <td>{{ presentation.start_date }}</td>
                        <td>{{ presentation.end_date }}</td>
                        {% if presentation.is_active %}
                            <td><a href="{% url 'courseapp:manage_presentation' presentation.id %}" class="btn btn-sm btn-dark" role="button">Manage</a></td>
                        {% else %}
                            <td><a href="{% url 'courseapp:manage_presentation' presentation.id %}" class="btn btn-sm btn-dark disabled" role="button" aria-disabled="true">Manage</a></td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h4>No available presentations found</h4>
    {% endif %}
{% endblock bodytag %}

src/homework/courseapp/templates/courseapp/homework_details.html
{% extends 'main/base.html' %}
{% block bodytag %}
    <h2>{{ homework.title }}</h2>
    <p>{{ homework.description }}</p>
    <hr>
    {% if homework.answers.all %}
        {% for answer in homework.homeworkstudentrel_set.all %}
            <div class="card">
                <div class="card-header">{{ answer.student }}</div>
                <div class="card-body">
                    <p class="card-text">{{ answer.answer }}</p>
                </div>
            </div>
            <br>
        {% endfor %}
    {% else %}
        <h4>No available answers found</h4>
    {% endif %}
{% endblock bodytag %}

src/homework/courseapp/templates/courseapp/lecture_details.html
{% extends 'main/base.html' %}
{% block bodytag %}
    <h2>{{ lecture }}</h2>
    <hr>
    <p>{{ lecture.text }}</p>
{% endblock bodytag %}

src/homework/courseapp/templates/courseapp/new_course.html
{% extends 'main/base.html' %}
{% block bodytag %}
    <h2 class="page-title">New course</h2>
    <hr>
    <form action="" method="POST" class="compact-form">
        {% csrf_token %}
        <div class="mb-3">
            <label for="name" class="form-label">Name:</label>
            {{ form.name }}
        </div>
        <div class="mb-3">
            <label for="description" class="form-label">Description:</label>
            {{ form.description }}
        </div>
        <input type="submit" class="btn btn-dark btn-sm" value="Add">
    </form>
{% endblock bodytag %}

src/homework/courseapp/templates/courseapp/new_lecture.html
{% extends 'main/base.html' %}
{% block bodytag %}
    <h2 class="page-title">New lecture</h2>
    <hr>
    <form action="" method="POST" class="compact-form">
        {% csrf_token %}
        <div class="mb-3">
            <label for="title" class="form-label">Title:</label>
            {{ form.title }}
        </div>
        <div class="mb-3">
            <label for="text" class="form-label">Text:</label>
            {{ form.text }}
        </div>
        <input type="submit" class="btn btn-dark btn-sm" value="Add">
    </form>
{% endblock bodytag %}

src/homework/courseapp/templates/courseapp/new_presentation.html
{% extends 'main/base.html' %}
{% block bodytag %}
    <h2 class="page-title">New presentation for {{ course_name }}</h2>
    <hr>
    <form action="" method="POST" class="compact-form">
        {% csrf_token %}
        <div class="mb-3">
            <label for="name" class="form-label">Start date:</label>
            {{ form.start_date }}
        </div>
        <div class="mb-3">
            <label for="description" class="form-label">End date:</label>
            {{ form.end_date }}
        </div>
        <input type="submit" class="btn btn-dark btn-sm" value="Add">
    </form>
{% endblock bodytag %}

src/homework/courseapp/templates/courseapp/presentation_dashboard.html
{% extends 'main/base.html' %}
{% load model_tags %}
{% block bodytag %}
    <h4>Homeworks</h4>
    <hr>
    {% if presentation.homework_set.all %}
        <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for homework in presentation.homework_set.all %}
            <div class="col" >
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ homework }}</h5>
                        <p class="card-text">{{ homework.description|truncatechars:256 }}</p>
                        {% if student|student_has_answered:homework %}
                            <a href="{% url 'courseapp:submit_answer' homework.id %}" class="btn btn-sm btn-dark disabled" role="button" aria-disabled="true">Already answered</a>
                        {% else %}
                            <a href="{% url 'courseapp:submit_answer' homework.id %}" class="btn btn-sm btn-dark" role="button">Answer</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <h4>No available homeworks found</h4>
    {% endif %}
    <br>
    <h4>Lectures</h4>
    <hr>
    {% if presentation.lecture_set.all %}
        <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for lecture in presentation.lecture_set.all %}
            <div class="col" >
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ lecture }}</h5>
                        <p class="card-text">{{ lecture.text|truncatechars:256 }}</p>
                        <a href="{% url 'courseapp:lecture_details' lecture.id %}" class="btn btn-sm btn-secondary" role="button">Details</a>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <h4>No lectures homeworks found</h4>
    {% endif %}
{% endblock bodytag %}

src/homework/courseapp/templates/courseapp/student_courses.html
{% extends 'main/base.html' %}
{% load model_tags %}
{% block bodytag %}
    {% if course_set %}
        <div class="row row-cols-1 row-cols-md-2 g-4">
            {% for course in course_set %}
                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">{{ course.course }}</h5>
                            <span class="card-text text-muted">{{ course.start_date }} - {{ course.end_date }}</span>
                            <br>
                            <p class="card-text">{{ course.course.description|truncatechars:256 }}</p>
                            {% if course|presentation_has_ended %}
                                <a href="{% url 'courseapp:certificate_details' course.id request.user.id %}" class="card-link btn btn-sm btn-dark" role="btn">Certificate</a>
                            {% elif course.is_active %}
                                <a href="{% url 'courseapp:course_dashboard' course.id %}" class="card-link btn btn-sm btn-dark" role="btn">Dashboard</a>
                            {% else %}
                                <a href="{% url 'courseapp:course_dashboard' course.id %}" class="card-link btn btn-sm btn-dark disabled" role="btn" aria-disabled="true">Dashboard</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h4>No available courses found</h4>
    {% endif %}
{% endblock bodytag %}

src/homework/courseapp/templates/courseapp/submit_answer.html
{% extends 'main/base.html' %}
{% block bodytag %}
    <h2 class="page-title">Submit answer</h2>
    <hr>
    <form action="" method="POST" class="compact-form">
        {% csrf_token %}
        <div class="mb-3">
            <label for="answer" class="form-label">Answer:</label>
            {{ form.answer }}
        </div>
        <input type="submit" class="btn btn-dark btn-sm" value="Submit">
    </form>
{% endblock bodytag %}

src/homework/courseapp/templates/courseapp/teacher_courses.html
{% extends 'main/base.html' %}
{% block bodytag %}
    <a href="{% url 'courseapp:new_course' %}" class="btn btn-dark">New course</a>
    <hr>
    {% if course_set %}
    <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for course in course_set %}
            <div class="col" >
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ course }}</h5>
                        <p class="card-text">{{ course.description|truncatechars:256 }}</p>
                        <a href="{% url 'courseapp:course_details' course.id %}" class="card-link btn btn-sm btn-secondary" role="btn">Details</a>
                        <a href="{% url 'courseapp:update_course' course.id %}" class="card-link btn btn-sm btn-dark" role="btn">Update</a>
                        <a href="{% url 'courseapp:course_presentations' course.id %}" class="card-link btn btn-sm btn-dark" role="btn">Presentations</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% else %}
        <h4>No available courses found</h4>
    {% endif %}
{% endblock bodytag %}